name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli
      - name: Run markdownlint
        run: |
          markdownlint "**/*.md" --config devtools/.markdownlint.json

  sql-smoke:
    runs-on: ubuntu-latest
    needs: lint-markdown
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Bring up DB
        continue-on-error: true
        run: |
          docker-compose -f devtools/docker/docker-compose.yml up -d --build
      - name: Run smoke tests
        run: |
          chmod +x devtools/tests/sql-smoke/run_tests.sh
          ./devtools/tests/sql-smoke/run_tests.sh
      - name: Tear down
        if: always()
        run: |
          docker-compose -f devtools/docker/docker-compose.yml down -v
